services:
  checkout-cache-cluster:
    container_name: checkout-cache-cluster
    image: grokzen/redis-cluster:6.2.14
    ports:
    - "6000:6000"
    - "6001:6001"
    - "6002:6002"
    - "6003:6003"
    - "6004:6004"
    - "6005:6005"
    environment:
      - IP=0.0.0.0
      - INITIAL_PORT=6000

  inventory-cache:
    container_name: inventory-cache
    image: redis:6-alpine
    ports:
    - "6379:6379"
